# Generated by Django 4.0.2 on 2022-02-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
