# Generated by Django 4.0.2 on 2022-02-17 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_remove_jobgroup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timereport',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='timereport',
            name='hoursWorked',
        ),
        migrations.CreateModel(
            name='TimeReportLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoursWorked', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='timeReports', to='payroll.employee')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportLines', to='payroll.timereport')),
            ],
        ),
    ]
