# Generated by Django 4.0.2 on 2022-02-17 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_remove_timereport_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timereportline',
            name='date',
            field=models.DateField(default=datetime.date(2022, 2, 17)),
        ),
    ]
